<a href="https://colab.research.google.com/github/bagariya-yogesh/email_spam_classifier/blob/master/email_spam_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Description: This predicts if the email is spam or not (0, 1)

In [ ]:
# Import libraries / dependencies
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

In [ ]:
# Load the data
from google.colab import files
uploaded = files.upload()

Saving emails.csv to emails.csv


In [ ]:
# Read the data
df = pd.read_csv('emails.csv')

df.head(5)

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [ ]:
# Print the shape
print(df.shape)
# columns name
df.columns

(5728, 2)


Index(['text', 'spam'], dtype='object')

In [ ]:
# Remove the Duplicates
df.drop_duplicates(inplace = True)

In [ ]:
# New shape
df.shape

(5695, 2)

In [ ]:
# Checking if there is a missing Data (NAN, nan, Nan, NA, na) for each column
df.isnull().sum()

text    0
spam    0
dtype: int64

In [ ]:
# Download the stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
def process_text(text):

  #1 Remove punctuation
  #2 Remove stopwords
  #3 return directory

  nopunc = [char for char in text if char not in string.punctuation]
  nopunc = ''.join(nopunc) 
  clean_words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

  return clean_words

In [ ]:
# tokenization (lemmatization)
df['text'].head().apply(process_text)

0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

In [ ]:
# Converting the text into matrix of tokens
from sklearn.feature_extraction.text import CountVectorizer
message_bow = CountVectorizer(analyzer=process_text).fit_transform(df['text'])

In [ ]:
# Split the data for training and testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(message_bow, df['spam'], test_size = .2, random_state = 0)

In [ ]:
# Get the shape of message_bow
message_bow.shape

(5695, 37229)

In [ ]:
# Create and train the naive bayes algorithm
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(X_train, y_train)

In [ ]:
# Print the prediction
print(classifier.predict(X_train))

# Print the actual values
print(y_train.values)


[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [ ]:
# Evaluate
from sklearn.metrics import accuracy_score
pred = classifier.predict(X_train)
print('Accuracy Score: ', accuracy_score(y_train, pred))


Accuracy Score:  0.9971466198419666


In [ ]:
# Evaluating on test data
predicted = classifier.predict(X_test)

print(predicted)
print()
print(y_test.values)

[1 0 0 ... 0 0 0]

[1 0 0 ... 0 0 0]


In [ ]:
pred = classifier.predict(X_test)
print('Accuracy Score: ', accuracy_score(y_test, pred))

Accuracy Score:  0.9920983318700615
